### ISSUE TITLE
Please relax overspecified version constraint on base for GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [hslua/hslua-module-text#1]
The current version does not allow building with base-4.11, which prevents GHC 8.4.1 from building this code. Once the constraint is removed, however, everything compiles fine! Could you please release an update on Hackage that remedies this issue?

**Comment by tarleb** [comment]
Thanks for the note!

I fixed the cabal file and created a new revision on hackage.

**Comment by peti** [comment]
Very cool, thank you!
